# Generated by Django 4.0.5 on 2022-06-22 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_slider_status_alter_product_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
