# Generated by Django 4.0.5 on 2022-06-22 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_ad_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='labels',
            field=models.CharField(blank=True, choices=[('special', 'special'), ('', 'default')], max_length=100),
        ),
        migrations.AddField(
            model_name='category',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'active'), ('', 'default')], max_length=100),
        ),
    ]
