# Generated by Django 4.0.5 on 2022-06-27 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
