# Generated by Django 4.0.5 on 2022-06-29 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_product_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='qunantity',
            new_name='quantity',
        ),
    ]
