# Generated by Django 4.0.5 on 2022-06-30 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_rename_qunantity_cart_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='checkout',
            field=models.BooleanField(default=1),
        ),
    ]
