# Generated by Django 4.0.5 on 2022-06-30 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_cart_checkout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='checkout',
            field=models.BooleanField(default=False),
        ),
    ]
